### ISSUE TITLE
Struct pointer arithmetic

### ISSUE THREAD

**Issue by souragc** [checkedc/checkedc#504]
I have the following code:

```c
typedef struct {
  char z;
} A;

typedef struct {
  A a;
} B;

void func(A *a) {
  B *b = (B*)((char*)a - offsetof(B, a));
}

int main() {
  B b;
  func(&b.a);
}
```
What is the best way to convert this into Checked C? For function `func`, it doesn't make sense to make `a` as and `_Array_ptr` of count 1 since the calculation afterward will go beyond its bounds.

**Comment by dtarditi** [comment]
In general, you can't expand bounds for a pointer.  The only exception to this is for pointers to null-terminated arrays.   This means that the bounds for the parameter `a` in `func` must be wide enough for a value of type `B`.   Bounds expressions can be any non-modifying C expression.   So you could give `a` a bounds wide enough for a value of type`B`:
```
void func(A *a : bounds((char *) a - offsetof(B, a), (char *) a - offsetof(B, a) + sizeof(B)))
```
In the example you give, since `a` is the first and only field of `B`, you could simplify this code to:
```
void func(A *a :bytecount(sizeof(B))
```
In general, taking an interior pointer to a member of a structure and then trying to cast it to point to the enclosing structure will be awkward.   The information establishing the correctness of the cast with respect to bounds must be encoded into the bounds information.

**Comment by souragc** [comment]
I will try it out. Thank you, David.
